#version 460

layout(local_size_x=16,local_size_y=16,local_size_z=1)in;

layout(set=0,binding=0,rgba16f)uniform writeonly image2D outputImage;

layout(push_constant)uniform WaterComputeTimePushConstants
{
    float time;
    float deltaTime;
}
push;

void main()
{
    vec3 color=vec3(1.,0.,0.);// Example color, replace with actual shading logic
    ivec2 texel=ivec2(gl_GlobalInvocationID.xy);
    imageStore(outputImage,texel,vec4(color,1.));
}