#pragma once

#include <cstddef>
#include <unordered_map>

#include "TypeDescriptor.hpp"

namespace Faye::Ecs
{
    // Runtime half of the semantic system: TypeId -> the four operations a
    // generic walker needs. The compile-time half is SemanticTraits in
    // TypeDescriptor.hpp; the two meet at the TypeId.
    //
    // This is the extension point that keeps Layout closed. A new value type
    // costs one FAYE_SEMANTIC line beside its definition and one registration
    // below -- no enum edits, no changes to Describe.hpp, no changes to any
    // walker.
    struct SemanticOps
    {
        void (*serialize)(const void *field, const char *name, Serializer &) = nullptr;
        void (*deserialize)(void *field, const char *name, Deserializer &) = nullptr;

        // Same value with no key, for one element of a sequence. The reader is
        // bound to the element's own node, hence const and no name.
        //
        // Generated by the same makeOps<T>() as the pair above, so supporting
        // vector<T> costs nothing per type -- only the two adapter lines that
        // every semantic already needs.
        void (*serializeElement)(const void *field, Serializer &) = nullptr;
        void (*deserializeElement)(void *field, const Deserializer &) = nullptr;

        void (*defaultInto)(void *field) = nullptr;
        bool (*equals)(const void *a, const void *b) = nullptr;

        // Reserved for 1.11 (inspector). Declared now so adding the editor does
        // not churn this struct; returns true when the widget edited the value.
        bool (*draw)(void *field, const FieldDescriptor &) = nullptr;
    };

    class SemanticRegistry
    {
    public:
        // Built-ins are installed on first use, so there is no static
        // initialisation order to get wrong and headless tests need no setup.
        static SemanticRegistry &instance();

        // Trailing underscore: `register` is a keyword.
        void register_(TypeId id, const SemanticOps &ops);

        // Null when the id is unregistered -- callers fall back to Layout.
        const SemanticOps *find(TypeId id) const;

        size_t size() const { return ops.size(); }

    private:
        std::unordered_map<TypeId, SemanticOps> ops;
    };
}
